## 0. Setup

In [2]:
# If needed, run in a notebook cell:
# %pip install pandas numpy openpyxl

import numpy as np
import pandas as pd

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.6
NumPy: 2.4.6

## 13. Series and DataFrame

In [3]:
series = pd.Series([80, 92, 75], index=["Ali", "Sara", "Omar"], name="score")
print(series)
print("Sara's score:", series.loc["Sara"])

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Omar"],
    "age": [22, 25, 23],
    "score": [80, 92, 75]
})
display(df)

Ali     80
Sara    92
Omar    75
Name: score, dtype: int64
Sara's score: 92

   name  age  score
0   Ali   22     80
1  Sara   25     92
2  Omar   23     75

**Core idea:** A `Series` is a labelled one-dimensional structure. A `DataFrame` is a table of labelled rows and columns.

## 14. Inspecting a DataFrame

In [4]:
import sys
import numpy as np
import pandas as pd

print("Python:", sys.executable)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

Python: c:\Users\Zain\OneDrive\Desktop\mirzajamalnasir750\.venv\Scripts\python.exe
NumPy: 2.4.6
Pandas: 3.0.6

In [5]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmed", "Sara", "Jamal"],
    "Age": [25, 30, 22, 28],
    "Salary": [30000, 45000, 28000, 50000]
}

df = pd.DataFrame(data)

display(df)
display(df.describe())
df.info()

    Name  Age  Salary
0    Ali   25   30000
1  Ahmed   30   45000
2   Sara   22   28000
3  Jamal   28   50000

         Age        Salary
count   4.00      4.000000
mean   26.25  38250.000000
std     3.50  10904.891869
min    22.00  28000.000000
25%    24.25  29500.000000
50%    26.50  37500.000000
75%    28.50  46250.000000
max    30.00  50000.000000

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [6]:
import numpy as np

print(np.__version__)
print(np.array([10, 20, 30]))
print(df.head())
print(df.tail(2))
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.info()
display(df.describe(include="number"))

2.4.6
[10 20 30]
    Name  Age  Salary
0    Ali   25   30000
1  Ahmed   30   45000
2   Sara   22   28000
3  Jamal   28   50000
    Name  Age  Salary
2   Sara   22   28000
3  Jamal   28   50000
(4, 3)
['Name', 'Age', 'Salary']
Name        str
Age       int64
Salary    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

         Age        Salary
count   4.00      4.000000
mean   26.25  38250.000000
std     3.50  10904.891869
min    22.00  28000.000000
25%    24.25  29500.000000
50%    26.50  37500.000000
75%    28.50  46250.000000
max    30.00  50000.000000

## 15. Selecting columns, rows, and cells

In [7]:
# 1. One column -> Series
print(df["Name"])

# 2. Multiple columns -> DataFrame
display(df[["Name", "Salary"]])

# 3. Row by index label
display(df.loc[0])

# 4. Row by integer position
display(df.iloc[0])

# 5. Row label 1, column Name
print(df.loc[1, "Name"])

# 6. First row, third column
print(df.iloc[0, 2])

0      Ali
1    Ahmed
2     Sara
3    Jamal
Name: Name, dtype: str

    Name  Salary
0    Ali   30000
1  Ahmed   45000
2   Sara   28000
3  Jamal   50000

Name        Ali
Age          25
Salary    30000
Name: 0, dtype: object

Name        Ali
Age          25
Salary    30000
Name: 0, dtype: object

Ahmed
30000

In [9]:
df

    Name  Age  Salary
0    Ali   25   30000
1  Ahmed   30   45000
2   Sara   22   28000
3  Jamal   28   50000

In [8]:
display(df.loc[0])

Name        Ali
Age          25
Salary    30000
Name: 0, dtype: object

### Filter rows

In [32]:
display(df[df["Salary"] >= 30000])

display(df[(df["Age"] >= 23) & (df["Salary"] > 30000)])

display(df[df["Name"].isin(["Ali", "Jamal"])])

    Name  Age  Salary
0    Ali   25   30000
1  Ahmed   30   45000
3  Jamal   28   50000

    Name  Age  Salary
1  Ahmed   30   45000
3  Jamal   28   50000

    Name  Age  Salary
0    Ali   25   30000
3  Jamal   28   50000

## 16. Add, update, and remove columns

In [10]:
df_work = df.copy()

df_work["passed"] = df_work["Salary"] >= 30000

## 17. Sorting and ranking

In [34]:
display(df.sort_values("Salary", ascending=False))

df_ranked = df.assign(
    rank=df["Salary"].rank(method="dense", ascending=False)
)

display(df_ranked)

    Name  Age  Salary
3  Jamal   28   50000
1  Ahmed   30   45000
0    Ali   25   30000
2   Sara   22   28000

    Name  Age  Salary  rank
0    Ali   25   30000   3.0
1  Ahmed   30   45000   2.0
2   Sara   22   28000   4.0
3  Jamal   28   50000   1.0

## 18. Missing values

In [35]:
messy = pd.DataFrame({
    "name": ["Ali", "Sara", "Omar", "Mina"],
    "age": [22, np.nan, 23, np.nan],
    "score": [80, 92, np.nan, 70],
    "city": ["London", "Leeds", None, "London"]
})
display(messy)
print(messy.isna().sum())
display(messy.dropna())
display(messy.fillna({"age": messy["age"].median(),
                      "score": messy["score"].mean(),
                      "city": "Unknown"}))

   name   age  score    city
0   Ali  22.0   80.0  London
1  Sara   NaN   92.0   Leeds
2  Omar  23.0    NaN     NaN
3  Mina   NaN   70.0  London

name     0
age      2
score    1
city     1
dtype: int64

  name   age  score    city
0  Ali  22.0   80.0  London

   name   age      score     city
0   Ali  22.0  80.000000   London
1  Sara  22.5  92.000000    Leeds
2  Omar  23.0  80.666667  Unknown
3  Mina  22.5  70.000000   London

Choose how to handle missing values based on context. Filling numeric data with a mean or median is not automatically correct; consider why values are missing and whether missingness itself is informative.

## 19. Duplicates and data types

In [36]:
duplicates = pd.DataFrame({
    "id": [1, 2, 2, 3],
    "name": ["Ali", "Sara", "Sara", "Omar"]
})
print("Duplicate rows:", duplicates.duplicated().sum())
display(duplicates.drop_duplicates())
duplicates["id"] = duplicates["id"].astype("int64")

Duplicate rows: 1

   id  name
0   1   Ali
1   2  Sara
3   3  Omar

## 20. String operations

In [1]:
people = pd.DataFrame({
    "name": ["  ALI Khan ", "Sara Ahmed", "omar malik", None],
    "email": ["ALI@EXAMPLE.COM", "sara@example.com", "omar@example.com", None]
})
people["name_clean"] = people["name"].str.strip().str.title()
people["email_clean"] = people["email"].str.lower()
people["has_example_email"] = people["email"].str.contains("example.com", na=False)
display(people)

NameError: name 'pd' is not defined

## 21. GroupBy and aggregation

In [38]:
sales = pd.DataFrame({
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "employee": ["A", "B", "C", "D", "E", "F"],
    "salary": [40000, 50000, 35000, 37000, 42000, 46000],
    "years": [2, 5, 3, 4, 1, 6]
})
display(sales.groupby("department")["salary"].mean().sort_values(ascending=False))
display(sales.groupby("department").agg(
    average_salary=("salary", "mean"),
    maximum_salary=("salary", "max"),
    employee_count=("employee", "count"),
    average_experience=("years", "mean")
).reset_index())

department
IT       45000.0
Sales    44000.0
HR       36000.0
Name: salary, dtype: float64

,department,average_salary,maximum_salary,employee_count,average_experience
0,HR,36000.0,37000,2,3.5
1,IT,45000.0,50000,2,3.5
2,Sales,44000.0,46000,2,3.5

## 22. Merge, join, and concatenate

In [39]:
employees = pd.DataFrame({"employee_id": [1, 2, 3], "name": ["Ali", "Sara", "Omar"]})
payroll = pd.DataFrame({"employee_id": [1, 2, 4], "salary": [40000, 50000, 60000]})

display(employees.merge(payroll, on="employee_id", how="inner"))
display(employees.merge(payroll, on="employee_id", how="left"))
display(employees.merge(payroll, on="employee_id", how="outer", indicator=True))

north = pd.DataFrame({"city": ["Leeds"], "sales": [100]})
south = pd.DataFrame({"city": ["London"], "sales": [200]})
display(pd.concat([north, south], ignore_index=True))

   employee_id  name  salary
0            1   Ali   40000
1            2  Sara   50000

   employee_id  name   salary
0            1   Ali  40000.0
1            2  Sara  50000.0
2            3  Omar      NaN

   employee_id  name   salary      _merge
0            1   Ali  40000.0        both
1            2  Sara  50000.0        both
2            3  Omar      NaN   left_only
3            4   NaN  60000.0  right_only

     city  sales
0   Leeds    100
1  London    200

**Join types:** `inner` keeps matching keys, `left` keeps all left rows, `right` keeps all right rows, and `outer` keeps all keys from both tables.

## 23. Dates and time series

In [40]:
dates = pd.DataFrame({
    "date": ["2026-01-03", "2026-02-14", "not-a-date"],
    "sales": [100, 150, 80]
})
dates["date"] = pd.to_datetime(dates["date"], errors="coerce")
dates["year"] = dates["date"].dt.year
dates["month"] = dates["date"].dt.month
dates["weekday"] = dates["date"].dt.day_name()
display(dates)

        date  sales    year  month   weekday
0 2026-01-03    100  2026.0    1.0  Saturday
1 2026-02-14    150  2026.0    2.0  Saturday
2        NaT     80     NaN    NaN       NaN

### Resampling dated observations

In [41]:
daily = pd.DataFrame({
    "date": pd.date_range("2026-01-01", periods=10, freq="D"),
    "value": [10, 12, 9, 15, 11, 18, 17, 13, 16, 20]
}).set_index("date")

display(daily.resample("W")["value"].mean())

date
2026-01-04    11.500000
2026-01-11    15.833333
Freq: W-SUN, Name: value, dtype: float64

## 24. Pivot tables and crosstabs

In [42]:
transactions = pd.DataFrame({
    "region": ["North", "North", "South", "South", "North", "South"],
    "product": ["A", "B", "A", "B", "A", "A"],
    "revenue": [100, 150, 120, 180, 90, 130]
})
display(pd.pivot_table(transactions, values="revenue", index="region",
                       columns="product", aggfunc="sum", fill_value=0))
display(pd.crosstab(transactions["region"], transactions["product"]))

product    A    B
region
North    190  150
South    250  180

product  A  B
region
North    2  1
South    2  1

## 25. Categorical data and memory

In [43]:
levels = ["low", "medium", "high"]
priority = pd.Series(pd.Categorical(
    ["low", "high", "medium", "low"],
    categories=levels,
    ordered=True
))
print(priority.sort_values())
print("Memory usage (bytes):")
print(df.memory_usage(deep=True))

0       low
3       low
2    medium
1      high
dtype: category
Categories (3, str): ['low' < 'medium' < 'high']
Memory usage (bytes):
Index     132
Name      245
Age        32
Salary     32
dtype: int64

## 26. `apply`, `map`, and vectorised alternatives

In [44]:
sample = pd.DataFrame({"price": [10, 20, 30, 40]})
sample["tax_vectorised"] = sample["price"] * 0.2
sample["tax_apply"] = sample["price"].apply(lambda value: value * 0.2)
display(sample)

   price  tax_vectorised  tax_apply
0     10             2.0        2.0
1     20             4.0        4.0
2     30             6.0        6.0
3     40             8.0        8.0

Prefer vectorised operations such as `df["price"] * 0.2` when possible. `apply` is useful for some custom operations, but it is not automatically faster.

## 27. MultiIndex basics

In [45]:
multi = sales.set_index(["department", "employee"]).sort_index()
display(multi)
print(multi.loc[("IT", "A")])
display(multi.reset_index())

                     salary  years
department employee
HR         C          35000      3
           D          37000      4
IT         A          40000      2
           B          50000      5
Sales      E          42000      1
           F          46000      6

salary    40000
years         2
Name: (IT, A), dtype: int64

  department employee  salary  years
0         HR        C   35000      3
1         HR        D   37000      4
2         IT        A   40000      2
3         IT        B   50000      5
4      Sales        E   42000      1
5      Sales        F   46000      6

## 28. Efficient data handling

- Select only the columns you need.
- Filter early when it reduces the data you must process.
- Use vectorised operations instead of Python loops where practical.
- Set suitable data types; categorical types can help for repeated labels.
- Read large files in chunks with `pd.read_csv(..., chunksize=...)`.
- Avoid chained assignment. Use `.loc[rows, columns] = value`.
- Profile before optimising; readability matters too.

In [46]:
# Example: chunked CSV processing (uncomment and adapt to your file)
# total_rows = 0
# for chunk in pd.read_csv("large_file.csv", chunksize=100_000):
#     total_rows += len(chunk)
# print(total_rows)

## 29. Exporting data

In [47]:
# Uncomment to write files into your current working directory:
# df.to_csv("students_clean.csv", index=False)
# df.to_excel("students_clean.xlsx", index=False)
# df.to_json("students_clean.json", orient="records", indent=2)

# Part III — Mini project: clean and analyse a dataset

In [48]:
raw = pd.DataFrame({
    "student": ["Ali", "Sara", "Omar", "Mina", "Sara"],
    "course": ["Python", "Python", "Data Science", "Data Science", "Python"],
    "score": [78, 92, np.nan, 68, 92],
    "study_hours": [4.0, 7.5, 3.0, np.nan, 7.5],
    "city": ["London", "Leeds", "London", None, "Leeds"]
})

print("Raw data:")
display(raw)

clean = raw.drop_duplicates().copy()
clean["score"] = clean["score"].fillna(clean["score"].median())
clean["study_hours"] = clean["study_hours"].fillna(clean["study_hours"].median())
clean["city"] = clean["city"].fillna("Unknown")
clean["passed"] = clean["score"] >= 70

print("Clean data:")
display(clean)

print("Summary by course:")
display(clean.groupby("course").agg(
    students=("student", "count"),
    average_score=("score", "mean"),
    pass_rate=("passed", "mean"),
    average_study_hours=("study_hours", "mean")
).reset_index())

print("Correlation between study hours and score:")
print(clean[["study_hours", "score"]].corr())

Raw data:

  student        course  score  study_hours    city
0     Ali        Python   78.0          4.0  London
1    Sara        Python   92.0          7.5   Leeds
2    Omar  Data Science    NaN          3.0  London
3    Mina  Data Science   68.0          NaN     NaN
4    Sara        Python   92.0          7.5   Leeds

Clean data:

  student        course  score  study_hours     city  passed
0     Ali        Python   78.0          4.0   London    True
1    Sara        Python   92.0          7.5    Leeds    True
2    Omar  Data Science   78.0          3.0   London    True
3    Mina  Data Science   68.0          4.0  Unknown   False

Summary by course:

         course  students  average_score  pass_rate  average_study_hours
0  Data Science         2           73.0        0.5                 3.50
1        Python         2           85.0        1.0                 5.75

Correlation between study hours and score:
             study_hours     score
study_hours     1.000000  0.795977
score           0.795977  1.000000

**Think critically:** This is a teaching example, not a validated analysis. Median imputation and correlation can be misleading on very small datasets. Always examine the data and the problem before drawing conclusions.

## Pandas practice exercises

Try these yourself before checking the answer key:
1. Create a DataFrame with `name`, `age`, and `score`.
2. Select rows where score is at least 80.
3. Add a `passed` column where score is at least 50.
4. Group a sales table by category and calculate total sales.
5. Merge two DataFrames using a shared ID.
6. Convert a text column to lowercase and trim whitespace.
7. Parse a date column and extract its month.
8. Find and remove duplicate rows.
9. Fill missing numeric values with the median.
10. Create a pivot table showing total sales by region and product.

In [49]:
# Write your solutions below.

## Pandas exercise answer key

In [50]:
# 1
students = pd.DataFrame({
    "name": ["Ali", "Sara", "Omar"],
    "age": [22, 25, 23],
    "score": [75, 90, 48]
})
display(students)

# 2
display(students[students["score"] >= 80])

# 3
students["passed"] = students["score"] >= 50
display(students)

# 4
sales_example = pd.DataFrame({
    "category": ["A", "B", "A"],
    "sales": [100, 50, 75]
})
display(sales_example.groupby("category", as_index=False)["sales"].sum())

# 5
left = pd.DataFrame({"id": [1, 2], "name": ["Ali", "Sara"]})
right = pd.DataFrame({"id": [1, 2], "score": [70, 90]})
display(left.merge(right, on="id", how="inner"))

# 6
names = pd.Series(["  ALI ", "Sara  ", " omar"])
print(names.str.strip().str.lower())

# 7
dates = pd.to_datetime(pd.Series(["2026-01-05", "2026-03-20"]))
print(dates.dt.month)

# 8
duplicate_df = pd.DataFrame({"x": [1, 1, 2]})
print(duplicate_df.drop_duplicates())

# 9
missing_df = pd.DataFrame({"score": [10, np.nan, 30]})
missing_df["score"] = missing_df["score"].fillna(missing_df["score"].median())
display(missing_df)

# 10
pivot_example = pd.DataFrame({
    "region": ["North", "North", "South"],
    "product": ["A", "B", "A"],
    "sales": [10, 20, 30]
})
display(pd.pivot_table(
    
    pivot_example, values="sales", index="region",
    columns="product", aggfunc="sum", fill_value=0
))

   name  age  score
0   Ali   22     75
1  Sara   25     90
2  Omar   23     48

   name  age  score
1  Sara   25     90

   name  age  score  passed
0   Ali   22     75    True
1  Sara   25     90    True
2  Omar   23     48   False

  category  sales
0        A    175
1        B     50

   id  name  score
0   1   Ali     70
1   2  Sara     90

0     ali
1    sara
2    omar
dtype: str
0    1
1    3
dtype: int32
   x
0  1
2  2

   score
0   10.0
1   20.0
2   30.0

product   A   B
region
North    10  20
South    30   0

## Study tip
Practise using `.loc` for label-based selection, `.iloc` for position-based selection, and `.copy()` before making an independent modified DataFrame.